
export const actionTypes = {

    SET_BANNER: "SET_BANNER",
    FETCH_MOVIES_PAGINATION: "FETCH_MOVIES_PAGINATION",
    FETCH_MOVIES: "FETCH_MOVIES",

    LOGIN_USER: "LOGIN_USER",
    LOGOUT_USER: "LOGOUT_USER",
    REGISTER_USER: "REGISTER_USER",

    FETCH_THEATER: "FETCH_THEATER"
}


