
export const actionTypes = {

    SET_MOVIES: "SET_MOVIES",
    SET_MOVIES_PAGINATION: "SET_MOVIES_PAGINATION",
    SET_SINGLE_MOVIE: "SET_SINGLE_MOVIE",

    REGISTER_USER: "REGISTER_USER",
    LOGIN_USER: "LOGIN_USER",
    FETCH_USER: "FETCH_USER",
    LOGOUT_USER: "LOGOUT_USER",

    LOADING: "LOADING",
}


