
export const actionTypes = {

    SET_BANNER: "SET_BANNER",
    FETCH_MOVIES_PAGINATION: "FETCH_MOVIES_PAGINATION",
    FETCH_MOVIES: "FETCH_MOVIES",
    FETCH_MOVIE: "FETCH_MOVIE",

    PLAY_MODAL: "PLAY_MODAL",

    LOGIN_USER: "LOGIN_USER",
    LOGOUT_USER: "LOGOUT_USER",
    REGISTER_USER: "REGISTER_USER",
    FETCH_USER_INFO: "FETCH_USER_INFO",

    FETCH_THEATER: "FETCH_THEATER",
    FETCH_MOVIE_SCHEDULE: "FETCH_MOVIE_SCHEDULE",

    GET_BOOKING_INFO: "GET_BOOKING_INFO",
    GET_BOOKING_TICKET_INFO: "GET_BOOKING_TICKET_INFO",
    BOOKING_SEAT: "BOOKING_SEAT",
    FINISH_BOOKING: "FINISH_BOOKING",


    DISPLAY_LOADING: "DISPLAY_LOADING",
    HIDE_LOADING: "HIDE_LOADING",

    CHANGE_TAB: "CHANGE_TAB",
    CHANGE_TAB_TYPE: "CHANGE_TAB_TYPE",
}


